[versions]
kotlin = "1.6.10"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version = "1.9.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.5.1" }
androidx-material = { module = "com.google.android.material:material", version = "1.6.1" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.2" }

[plugins]
publish = { id = "com.gradle.plugin-publish", version = "1.0.0" }
